### ISSUE TITLE
commands fail on 1.4.6 when using ssh-agent

### ISSUE THREAD

**Issue by bahamas10** [joyent/node-manta#216]
when running `mls` or `mget` on node `v0.12.0` and node-manta `v1.4.6` i see

```
$ ./bin/mls 
mls: TypeError: msecs must be a number
```

tracking this down and dumping a stack trace, we can see

```
TypeError: msecs must be a number
    at Object.exports.enroll (timers.js:156:11)
    at Socket.setTimeout (net.js:329:12)
    at SSHAgentClient._request (/Users/dave/dev/node-manta/node_modules/ssh-agent/lib/ssh_agent_client.js:300:10)
    at SSHAgentClient.requestIdentities (/Users/dave/dev/node-manta/node_modules/ssh-agent/lib/ssh_agent_client.js:186:15)
    at sshAgentGetKey (/Users/dave/dev/node-manta/lib/auth.js:216:12)
    at Object.checkAgentForKey [as func] (/Users/dave/dev/node-manta/lib/auth.js:450:17)
    at /Users/dave/dev/node-manta/node_modules/vasync/lib/vasync.js:191:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
```

which is fixed by this

https://github.com/mcavage/node-ssh-agent/pull/5

**Comment by bahamas10** [comment]
the PR for `node-ssh-agent` has been merged

**Comment by davepacheco** [comment]
Thanks so much for debugging this!
