### ISSUE TITLE
MLS Should Return More Informative Message on DNS Failure

### ISSUE THREAD

**Issue by qdzlug** [joyent/node-manta#234]
When unable to resolve the manta URL, the `mls` command returns a message of "socket hang up".

```
[2015-08-12T23:11:57.534Z] TRACE: mls/MantaClient/9705 on 15ea2be9-ce5d-6be3-af33-c6f29e4fb00a (/home/ubuntu/.nvm/v0.10.26/lib/node_modules/manta/node_modules/restify/lib/clients/http_client.js:251 in rawRequest): request sent
    GET /dap/public/webrevs HTTP/1.1
    Host: us-east.manta.joyent.com
    accept: */*
    x-request-id: 366e1cff-fb25-4d2f-9d41-1624ee1d07e9
    user-agent: restify/2.8.1 (x64-linux; v8/3.14.5.9; OpenSSL/1.0.1e) node/0.10.26
    accept-version: ~1.0
    date: Wed, 12 Aug 2015 23:11:48 GMT
[2015-08-12T23:12:01.539Z] TRACE: mls/MantaClient/9705 on 15ea2be9-ce5d-6be3-af33-c6f29e4fb00a (/home/ubuntu/.nvm/v0.10.26/lib/node_modules/manta/node_modules/restify/lib/clients/http_client.js:173 in onError): Request failed (err.code=ECONNRESET)
    Error: socket hang up
        at createHangUpError (http.js:1472:15)
        at Socket.socketCloseListener (http.js:1522:23)
        at Socket.EventEmitter.emit (events.js:117:20)
        at TCP.close (net.js:465:12)
```

**Comment by davepacheco** [comment]
Specifically: in this case, the DNS server did not respond at all.  It's not that it responded that it could not resolve the name.

**Comment by stigok** [comment]
I would've liked to have gotten some better information myself. The `mget` command eventually gave me the answer to my problems.

```
$: mls ~~/public
mls: Error: socket hang up

$: mput -f /tmp/hello.txt ~~/stor/hello-foo
mput: BadRequestError

$: mget ~~/stor/hello-foo
mget: InvalidHeaderError: Invalid Signature Authorization header: clock skew of 7198.846s was greater than 300s
```
