### ISSUE TITLE
ConcurrentRequestError on concurrent PUTs to the same object

### ISSUE THREAD

**Issue by davepacheco** [joyent/node-manta#24]
I have a test that creates the same object concurrently from multiple clients.  It sometimes hits this:

    [2013-02-12T00:19:40.783Z] FATAL: tst.concurrent.js/15970 on 7fb31d24: TEST FAILED
        ConcurrentRequestError: /poseidon/stor/obj3 was being concurrently updated
            at ClientRequest.onResponse (/home/dap/marlin/node_modules/manta/node_modules/restify/lib/clients/http_client.js:88:38)
            at ClientRequest.g (events.js:192:14)
            at ClientRequest.EventEmitter.emit (events.js:96:17)
            at HTTPParser.parserOnIncomingClient (http.js:1462:7)
            at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
            at CleartextStream.socketOnData (http.js:1367:20)
            at CleartextStream.CryptoStream._push (tls.js:526:27)
            at SecurePair.cycle (tls.js:880:20)
            at EncryptedStream.CryptoStream.write (tls.js:267:13)
            at Socket.ondata (stream.js:38:26)

It should not be an error to PUT the same object concurrently from multiple clients.  One of them should "win", and the others get clobbered, and that's it.  (This would be a problem for any system which wanted to make sure that an object exists, and any of N components may try to create it at once.)

**Comment by davepacheco** [comment]
This is probably a dup of internal issue https://smartos.org/bugview/MORAY-320.
