### ISSUE TITLE
mchmod fails when role tag contains whitespace

### ISSUE THREAD

**Issue by askfongjojo** [joyent/node-manta#273]
For example,
```
$ mchmod -- +"nice role" ~~/stor
mchmod: InternalError: an unexpected error occurred
```
With debug enabled:
```
$ mchmod -- +"nice role" ~~/stor
{
  "name": "mchmod",
  "hostname": "joyadmins-MacBook-Pro-3.local",
  "pid": 89605,
  "component": "MantaClient",
  "path": "/angela.fong/stor?metadata=true",
  "req_id": "c336385c-e703-43db-aba3-3d1b449d65a3",
  "level": 20,
  "headers": {
    "role-tag": "Nice-Role,nice role",
    "accept": "*/*",
    "x-request-id": "c336385c-e703-43db-aba3-3d1b449d65a3",
    "transfer-encoding": "chunked"
  },
  "id": "c336385c-e703-43db-aba3-3d1b449d65a3",
  "query": {},
  "msg": "chattr: entered",
  "time": "2016-09-23T21:46:19.161Z",
  "v": 0
}
{
  "name": "mchmod",
  "hostname": "joyadmins-MacBook-Pro-3.local",
  "pid": 89605,
  "component": "MantaClient",
  "path": "/angela.fong/stor",
  "req_id": "c336385c-e703-43db-aba3-3d1b449d65a3",
  "level": 20,
  "err": {
    "message": "an unexpected error occurred",
    "name": "InternalError",
    "stack": "InternalError: an unexpected error occurred\n    at ClientRequest.onResponse (/sdc/node-manta/node_modules/restify-clients/lib/HttpClient.js:217:26)\n    at ClientRequest.g (events.js:180:16)\n    at ClientRequest.emit (events.js:95:17)\n    at HTTPParser.parserOnIncomingClient (http.js:1689:21)\n    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)\n    at CleartextStream.socketOnData (http.js:1584:20)\n    at CleartextStream.read [as _read] (tls.js:514:12)\n    at CleartextStream.Readable.read (_stream_readable.js:341:10)\n    at EncryptedStream.write [as _write] (tls.js:369:25)\n    at doWrite (_stream_writable.js:226:10)",
    "code": "InternalError"
  },
  "msg": "chattr: error",
  "time": "2016-09-23T21:46:19.512Z",
  "v": 0
}
mchmod: InternalError: an unexpected error occurred
```

**Comment by davepacheco** [comment]
This one, on the other hand, is a server error (and there's a muskie log entry with some information, but not all that much).
