### ISSUE TITLE
mput -p causes role-tags to be dropped from parent directory

### ISSUE THREAD

**Issue by askfongjojo** [joyent/node-manta#274]
This happens when there is a new subdirectory in the object path. For example,
```
$ mchmod +nice-role ~~/stor/asdf
$ minfo ~~/stor/asdf | grep role-tag
$ mput -p ~~/stor/asdf/aa/bb </dev/null
/angela.fong/stor/asdf/aa/bb                                                                                                0B                  
$ minfo ~~/stor/asdf | grep role-tag
$
```

With debug enabled, it becomes clear that when the CLI client hits a non-existing directory in the object path, it attempts to walk the whole chain to create the parents, and stops only when it finds one that already exists. But then it has gone one extra level unnecessarily and updated that existing directory with no role-tags passed in the header.
```
$ mput -p ~~/stor/asdf/aaa/bbb </dev/null
{"name":"mput","hostname":"joyadmins-MacBook-Pro-3.local","pid":89930,"component":"MantaClient","path":"/angela.fong/stor/asdf/aaa/bbb","req_id":"c1c7197f-6f7d-496e-afa9-b693c50c544a","level":20,"headers":{"accept":"application/json, */*","x-request-id":"c1c7197f-6f7d-496e-afa9-b693c50c544a"},"id":"c1c7197f-6f7d-496e-afa9-b693c50c544a","query":{},"msg":"info: entered","time":"2016-09-23T22:34:38.662Z","v":0}
{"name":"mput","hostname":"joyadmins-MacBook-Pro-3.local","pid":89930,"component":"MantaClient","path":"/angela.fong/stor/asdf/aaa/bbb","req_id":"d81658ed-ee90-471c-aa02-fa559daaabe5","level":20,"headers":{"accept":"application/json","content-type":"application/octet-stream","expect":"100-continue","x-request-id":"d81658ed-ee90-471c-aa02-fa559daaabe5","x-durability-level":2,"transfer-encoding":"chunked"},"id":"d81658ed-ee90-471c-aa02-fa559daaabe5","query":{},"_original_path":"/angela.fong/stor/asdf/aaa/bbb","msg":"put: entered","time":"2016-09-23T22:34:39.443Z","v":0}
/angela.fong/stor/asdf/aaa/bbb                                                                                              0B                  
{"name":"mput","hostname":"joyadmins-MacBook-Pro-3.local","pid":89930,"component":"MantaClient","path":"/angela.fong/stor/asdf/aaa/bbb","req_id":"d81658ed-ee90-471c-aa02-fa559daaabe5","level":20,"err":{"message":"/angela.fong/stor/asdf/aaa does not exist","name":"DirectoryDoesNotExistError","stack":"DirectoryDoesNotExistError: /angela.fong/stor/asdf/aaa does not exist\n    at ClientRequest.onResponse (/sdc/node-manta/node_modules/restify-clients/lib/HttpClient.js:217:26)\n    at ClientRequest.g (events.js:180:16)\n    at ClientRequest.emit (events.js:95:17)\n    at HTTPParser.parserOnIncomingClient (http.js:1689:21)\n    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)\n    at CleartextStream.socketOnData (http.js:1584:20)\n    at CleartextStream.read [as _read] (tls.js:514:12)\n    at CleartextStream.Readable.read (_stream_readable.js:341:10)\n    at EncryptedStream.write [as _write] (tls.js:369:25)\n    at doWrite (_stream_writable.js:226:10)","code":"DirectoryDoesNotExist"},"msg":"put: error","time":"2016-09-23T22:34:39.542Z","v":0}
{"name":"mput","hostname":"joyadmins-MacBook-Pro-3.local","pid":89930,"component":"MantaClient","path":"/angela.fong/stor/asdf/aaa/bbb","req_id":"d81658ed-ee90-471c-aa02-fa559daaabe5","level":20,"msg":"put with mkdirp: mkdirp","time":"2016-09-23T22:34:39.542Z","v":0}
{"name":"mput","hostname":"joyadmins-MacBook-Pro-3.local","pid":89930,"component":"MantaClient","path":"/angela.fong/stor/asdf/aaa","req_id":"3804dd96-3901-4ac3-a19d-d5f5b21940bc","level":20,"msg":"mkdirp: entered","time":"2016-09-23T22:34:39.543Z","v":0}
{"name":"mput","hostname":"joyadmins-MacBook-Pro-3.local","pid":89930,"component":"MantaClient","path":"/angela.fong/stor/asdf","req_id":"2ed5eba3-5da4-4b28-9d41-c11b3f73eb42","level":20,"headers":{"accept":"application/json","content-type":"application/json; type=directory","x-request-id":"2ed5eba3-5da4-4b28-9d41-c11b3f73eb42"},"id":"2ed5eba3-5da4-4b28-9d41-c11b3f73eb42","query":{},"msg":"mkdir: entered","time":"2016-09-23T22:34:39.543Z","v":0}
{"name":"mput","hostname":"joyadmins-MacBook-Pro-3.local","pid":89930,"component":"MantaClient","path":"/angela.fong/stor/asdf/aaa","req_id":"e33fe68c-76f9-4ea7-960a-10b1b4bf5106","level":20,"headers":{"accept":"application/json","content-type":"application/json; type=directory","x-request-id":"e33fe68c-76f9-4ea7-960a-10b1b4bf5106"},"id":"e33fe68c-76f9-4ea7-960a-10b1b4bf5106","query":{},"msg":"mkdir: entered","time":"2016-09-23T22:34:39.885Z","v":0}
{"name":"mput","hostname":"joyadmins-MacBook-Pro-3.local","pid":89930,"component":"MantaClient","path":"/angela.fong/stor/asdf/aaa","req_id":"3804dd96-3901-4ac3-a19d-d5f5b21940bc","level":20,"msg":"mkdirp: done","time":"2016-09-23T22:34:40.014Z","v":0}
{"name":"mput","hostname":"joyadmins-MacBook-Pro-3.local","pid":89930,"component":"MantaClient","path":"/angela.fong/stor/asdf/aaa/bbb","req_id":"d81658ed-ee90-471c-aa02-fa559daaabe5","level":20,"msg":"put with mkdirp: mkdirp done","time":"2016-09-23T22:34:40.014Z","v":0}
{"name":"mput","hostname":"joyadmins-MacBook-Pro-3.local","pid":89930,"component":"MantaClient","path":"/angela.fong/stor/asdf/aaa/bbb","req_id":"d81658ed-ee90-471c-aa02-fa559daaabe5","level":20,"msg":"put: continue received","time":"2016-09-23T22:34:40.122Z","v":0}
{"name":"mput","hostname":"joyadmins-MacBook-Pro-3.local","pid":89930,"component":"MantaClient","path":"/angela.fong/stor/asdf/aaa/bbb","req_id":"d81658ed-ee90-471c-aa02-fa559daaabe5","level":20,"msg":"put: done","time":"2016-09-23T22:34:40.229Z","v":0}
```

**Comment by cburroughs** [comment]
More generally this is a problem for all metadata.  If `mkdir` is operating on parent directories, it unconditional writes to all of them from the root.  As the comment says "Called mkdir, but really this is putdir, as it will let you call mkdir on an already existing directory."

I think https://cr.joyent.us/#/c/857 is a path towards fixing this issue.  While looking at this I noticed #283, which would also presumably trip people up working with `mput` and roles.

Example with patch, which I think matches the expected behavior:
```
$ ./bin/mmkdir ~~/stor/asdf
$ ./bin/mchmod +test-role-a ~~/stor/asdf
$ ./bin/minfo ~~/stor/asdf | grep role-tag
role-tag: test-role-a
$ ./bin/mput -p ~~/stor/asdf/aa/bb </dev/null
/cburroughs/stor/asdf/aa/bb                                                                                    0B   
$ ./bin/minfo ~~/stor/asdf | grep role-tag
role-tag: test-role-a
```
